esphome:
  name: bed-occupancy-sensor
  includes:
    - sensor.h
  libraries:
    - bogde/HX711
  project: 
    name: "dmitrij_patuk.bed_occupancy_sensor"
    version: "1.0.0"

#=====================CONFIGURE BOARD =====================================
    
esp8266:
  board: d1_mini

#=====================CONFIGURE CONNECTIVITY =====================================

<<: !include /base/base.yaml
    
#=====================REGISTER THE CUSTOM SENSOR ================================

sensor:
- platform: custom
  lambda: |-
    auto sensor = new CustomBedSensor();
    App.register_component(sensor);
    return {sensor->first_scale_sensor, sensor->second_scale_sensor};

#=====================DISPLAY OUTPUT OF THE CUSTOM SENSOR =======================
## TODO MQTT PUBLISH
