logger:

api:
  password: !secret api_password

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "Bed Occupancy Sensor"
    password: !secret fallback_ap_password

captive_portal:
