
substitutions:
  name: bed-occupancy-sensor
  project_name: "dmitrij_patuk.bed_occupancy_sensor"
  project_version: "1.0.0"

<<: !include base/d1_mini_base.yaml
<<: !include base/base.yaml
   
#Choose the communication platform. !!!ONLY USE MQTT OR API!!!
#<<: !include base/mqtt.yaml
<<: !include base/api.yaml
   
sensor:
  - platform: custom
    lambda: |-
      auto sensor = new CustomBedSensor();
      App.register_component(sensor);
      return {sensor->first_scale_sensor, sensor->second_scale_sensor};
    sensors:
      - name: "First Scale Sensor"
        unit_of_measurement: kg
        accuracy_decimals: 2
      - name: "Second Scale Sensor"
        unit_of_measurement: kg
        accuracy_decimals: 2
