
substitutions:
  name: bed-occupancy
  project_name: "dmitrij_patuk.bed_occupancy"
  project_version: "1.0.0"

<<: !include base/d1_mini_base.yaml
<<: !include base/base.yaml
   
#Choose the communication platform. !!!ONLY USE MQTT OR API!!!
#<<: !include base/mqtt.yaml
<<: !include base/api.yaml
   
sensor:
  - platform: custom
    lambda: |-
      auto sensor = new CustomBedSensor();
      App.register_component(sensor);
      return {sensor->first, sensor->second};
    sensors:
      - name: "First"
        unit_of_measurement: kg
        accuracy_decimals: 2
        filters:
          - lambda: return x / 1;        
      - name: "Second"
        unit_of_measurement: kg
        accuracy_decimals: 2
        filters:
          - lambda: return x / 1;        
